import sklearn
import csv
import pandas as pd
import numpy as np

#Import scikit-learn dataset library
from sklearn import datasets

#load dataset to a nympy-array
with open('Rörelser.csv', 'r') as file:
 har = list(csv.reader(file))
 har = np.array(har[2:], dtype=np.float)

# seperate data
data = pd.DataFrame( {
    'tBodyAcc-mean()-X': har[ :, 0 ],
    'tBodyAcc-mean()-Y': har[ :, 1 ],
    'tBodyAcc-mean()-Z': har[ :, 2 ],
    'tBodyAcc-std()-X': har[ :, 3 ],
    'tBodyAcc-std()-Y': har[ :, 4 ],
    'tBodyAcc-std()-Z': har[ :, 5 ],
    'tBodyAcc-mad()-X': har[ :, 6 ],
    'tBodyAcc-mad()-Y': har[ :, 7 ],
    'tBodyAcc-mad()-Z': har[ :, 8 ],
    'tBodyAcc-max()-X': har[ :, 9 ],
    'tBodyAcc-max()-Y': har[ :, 10 ],
    'tBodyAcc-max()-Z': har[ :, 11 ],
    'tBodyAcc-min()-X': har[ :, 12 ],
    'tBodyAcc-min()-Y': har[ :, 13 ],
    'tBodyAcc-min()-Z': har[ :, 14 ],
    'tBodyAcc-sma()': har[ :, 15 ],
    'tBodyAcc-energy()-X': har[ :, 16 ],
    'tBodyAcc-energy()-Y': har[ :, 17 ],
    'tBodyAcc-energy()-Y': har[ :, 18 ],
    'tBodyAcc-iqr()-X': har[ :, 19 ],
    'tBodyAcc-iqr()-Y': har[ :, 20 ],
    'tBodyAcc-iqr()-Z': har[ :, 21 ],
    'tBodyAcc-entropy()-X': har[ :, 22 ],
    'tBodyAcc-entropy()-Y': har[ :, 23 ],
    'tBodyAcc-entropy()-Z': har[ :, 24 ],
    'tBodyAcc-correlation()-X,Y': har[ :, 25 ],
    'tBodyAcc-correlation()-X,Z': har[ :, 26 ],
    'tBodyAcc-correlation()-Y,Z': har[ :, 27 ],
    'tGravityAcc-mean()-X': har[ :, 28 ],
    'tGravityAcc-mean()-Y': har[ :, 29 ],
    'tGravityAcc-mean()-Z': har[ :, 30 ],
    'tGravityAcc-std()-X': har[ :, 31 ],
    'tGravityAcc-std()-Y': har[ :, 32 ],
    'tGravityAcc-std()-Z': har[ :, 33 ],
    'tGravityAcc-mad()-X': har[ :, 34 ],
    'tGravityAcc-mad()-Y': har[ :, 35 ],
    'tGravityAcc-mad()-Z': har[ :, 36 ],
    'tGravityAcc-max()-X': har[ :, 37 ],
    'tGravityAcc-max()-Y': har[ :, 38 ],
    'tGravityAcc-max()-Z': har[ :, 39 ],
    'tGravityAcc-min()-X': har[ :, 40 ],
    'tGravityAcc-min()-Y': har[ :, 41 ],
    'tGravityAcc-min()-Z': har[ :, 42 ],
    'tGravityAcc-sma()': har[ :, 43 ],
    'tGravityAcc-energy()-X': har[ :, 44 ],
    'tGravityAcc-energy()-Y': har[ :, 45 ],
    'tGravityAcc-energy()-Z': har[ :, 46 ],
    'tGravityAcc-iqr()-X': har[ :, 47 ],
    'tGravityAcc-iqr()-Y': har[ :, 48 ],
    'tGravityAcc-iqr()-Z': har[ :, 49 ],
    'tGravityAcc-entropy()-X': har[ :, 50 ],
    'tGravityAcc-entropy()-Y': har[ :, 51 ],
    'tGravityAcc-entropy()-Z': har[ :, 52 ],
    'tGravityAcc-correlation()-X,Y': har[ :, 53 ],
    'tGravityAcc-correlation()-X,Z': har[ :, 54 ],
    'tGravityAcc-correlation()-Y,Z': har[ :, 55 ],
    'tBodyAccJerk-mean()-X': har[ :, 56 ],
    'tBodyAccJerk-mean()-Y': har[ :, 57 ],
    'tBodyAccJerk-mean()-Z': har[ :, 58 ],
    'tBodyAccJerk-std()-X': har[ :, 59 ],
    'tBodyAccJerk-std()-Y': har[ :, 60 ],
    'tBodyAccJerk-std()-Z': har[ :, 61 ],
    'tBodyAccJerk-mad()-X': har[ :, 62 ],
    'tBodyAccJerk-mad()-Y': har[ :, 63 ],
    'tBodyAccJerk-mad()-Z': har[ :, 64 ],
    'tBodyAccJerk-max()-X': har[ :, 65 ],
    'tBodyAccJerk-max()-Y': har[ :, 66 ],
    'tBodyAccJerk-max()-Z': har[ :, 67 ],
    'tBodyAccJerk-min()-X': har[ :, 68 ],
    'tBodyAccJerk-min()-Y': har[ :, 69 ],
    'tBodyAccJerk-min()-Z': har[ :, 70 ],
    'tBodyAccJerk-sma()': har[ :, 71 ],
    'tBodyAccJerk-energy()-X': har[ :, 72 ],
    'tBodyAccJerk-energy()-Y': har[ :, 73 ],
    'tBodyAccJerk-energy()-Y': har[ :, 74 ],
    'tBodyAccJerk-iqr()-X': har[ :, 75 ],
    'tBodyAccJerk-iqr()-Y': har[ :, 76 ],
    'tBodyAccJerk-iqr()-Z': har[ :, 77 ],
    'tBodyAccJerk-entropy()-X': har[ :, 78 ],
    'tBodyAccJerk-entropy()-Y': har[ :, 79 ],
    'tBodyAccJerk-entropy()-Z': har[ :, 80 ],
    'tBodyAccJerk-correlation()-X,Y': har[ :, 81 ],
    'tBodyAccJerk-correlation()-X,Z': har[ :, 82 ],
    'tBodyAccJerk-correlation()-Y,Z': har[ :, 83 ],
    'tBodyGyro-mean()-X': har[ :, 84 ],
    'tBodyGyro-mean()-Y': har[ :, 85 ],
    'tBodyGyro-mean()-Z': har[ :, 86 ],
    'tBodyGyro-std()-X': har[ :, 87 ],
    'tBodyGyro-std()-Y': har[ :, 88 ],
    'tBodyGyro-std()-Z': har[ :, 89 ],
    'tBodyGyro-mad()-X': har[ :, 90 ],
    'tBodyGyro-mad()-Y': har[ :, 91 ],
    'tBodyGyro-mad()-Z': har[ :, 92 ],
    'tBodyGyro-max()-X': har[ :, 93 ],
    'tBodyGyro-max()-Y': har[ :, 94 ],
    'tBodyGyro-max()-Z': har[ :, 95 ],
    'tBodyGyro-min()-X': har[ :, 96 ],
    'tBodyGyro-min()-Y': har[ :, 97 ],
    'tBodyGyro-min()-Z': har[ :, 98 ],
    'tBodyGyro-sma()': har[ :, 99 ],
    'tBodyGyro-energy()-X': har[ :, 100 ],
    'tBodyGyro-energy()-Y': har[ :, 101 ],
    'tBodyGyro-energy()-Y': har[ :, 102 ],
    'tBodyGyro-iqr()-X': har[ :, 103 ],
    'tBodyGyro-iqr()-Y': har[ :, 104 ],
    'tBodyGyro-iqr()-Z': har[ :, 105 ],
    'tBodyGyro-entropy()-X': har[ :, 106 ],
    'tBodyGyro-entropy()-Y': har[ :, 107 ],
    'tBodyGyro-entropy()-Z': har[ :, 108 ],
    'tBodyGyro-correlation()-X,Y': har[ :, 109 ],
    'tBodyGyro-correlation()-X,Z': har[ :, 110 ],
    'tBodyGyro-correlation()-Y,Z': har[ :, 111 ],
    'tBodyGyroJerk-mean()-X': har[ :, 112 ],
    'tBodyGyroJerk-mean()-Y': har[ :, 113 ],
    'tBodyGyroJerk-mean()-Z': har[ :, 114 ],
    'tBodyGyroJerk-std()-X': har[ :, 115 ],
    'tBodyGyroJerk-std()-Y': har[ :, 116 ],
    'tBodyGyroJerk-std()-Z': har[ :, 117 ],
    'tBodyGyroJerk-mad()-X': har[ :, 118 ],
    'tBodyGyroJerk-mad()-Y': har[ :, 119 ],
    'tBodyGyroJerk-mad()-Z': har[ :, 120 ],
    'tBodyGyroJerk-max()-X': har[ :, 121 ],
    'tBodyGyroJerk-max()-Y': har[ :, 122 ],
    'tBodyGyroJerk-max()-Z': har[ :, 123 ],
    'tBodyGyroJerk-min()-X': har[ :, 124 ],
    'tBodyGyroJerk-min()-Y': har[ :, 125 ],
    'tBodyGyroJerk-min()-Z': har[ :, 126 ],
    'tBodyGyroJerk-sma()': har[ :, 127 ],
    'tBodyGyroJerk-energy()-X': har[ :, 128 ],
    'tBodyGyroJerk-energy()-Y': har[ :, 129 ],
    'tBodyGyroJerk-energy()-Y': har[ :, 130 ],
    'tBodyGyroJerk-iqr()-X': har[ :, 131 ],
    'tBodyGyroJerk-iqr()-Y': har[ :, 132 ],
    'tBodyGyroJerk-iqr()-Z': har[ :, 133 ],
    'tBodyGyroJerk-entropy()-X': har[ :, 134 ],
    'tBodyGyroJerk-entropy()-Y': har[ :, 135 ],
    'tBodyGyroJerk-entropy()-Z': har[ :, 136 ],
    'tBodyGyroJerk-correlation()-X,Y': har[ :, 137 ],
    'tBodyGyroJerk-correlation()-X,Z': har[ :, 138 ],
    'tBodyGyroJerk-correlation()-Y,Z': har[ :, 139 ],
    'tBodyAccMag-mean()': har[ :, 140 ],
    'tBodyAccMag-std()': har[ :, 141 ],
    'tBodyAccMag-mad()': har[ :, 142 ],
    'tBodyAccMag-max()': har[ :, 143 ],
    'tBodyAccMag-min()': har[ :, 144 ],
    'tBodyAccMag-sma()': har[ :, 145 ],
    'tBodyAccMag-energy()': har[ :, 146 ],
    'tBodyAccMag-iqr()': har[ :, 147 ],
    'tBodyAccMag-enropy()': har[ :, 148 ],
    'tGravityAccMag-mean()': har[ :, 149 ],
    'tGravityAccMag-std()': har[ :, 150 ],
    'tGravityAccMag-mad()': har[ :, 151 ],
    'tGravityAccMag-max()': har[ :, 152 ],
    'tGravityAccMag-min()': har[ :, 153 ],
    'tGravityAccMag-sma()': har[ :, 154 ],
    'tGravityAccMag-energy()': har[ :, 155 ],
    'tGravityAccMag-iqr()': har[ :, 156 ],
    'tGravityAccMag-entropy()': har[ :, 157 ],
    'tBodyAccJerkMag-mean()': har[ :, 158 ],
    'tBodyAccJerkMag-std()': har[ :, 159 ],
    'tBodyAccJerkMag-mad()': har[ :, 160 ],
    'tBodyAccJerkMag-max()': har[ :, 161 ],
    'tBodyAccJerkMag-min()': har[ :, 162 ],
    'tBodyAccJerkMag-sma()': har[ :, 163 ],
    'tBodyAccJerkMag-energy()': har[ :, 164 ],
    'ttBodyAccJerkMag-iqr()': har[ :, 165 ],
    'tBodyAccJerkMag-entropy()': har[ :, 166 ],
    'tBodyGyroMag-mean()': har[ :, 167 ],
    'tBodyGyroMag-std()': har[ :, 168 ],
    'tBodyGyroMag-mad()': har[ :, 169 ],
    'tBodyGyroMag-max()': har[ :, 170 ],
    'tBodyGyroMag-min()': har[ :, 171 ],
    'tBodyGyroMag-sma()': har[ :, 172 ],
    'tBodyGyroMag-energy()': har[ :, 173 ],
    'ttBodyGyroMag-iqr()': har[ :, 174 ],
    'tBodyGyroMag-entropy()': har[ :, 175 ],
    'tBodyGyroJerkMag-mean()': har[ :, 176 ],
    'tBodyGyroJerkMag-std()': har[ :, 177 ],
    'tBodyGyroJerkMag-mad()': har[ :, 178 ],
    'tBodyGyroJerkMag-max()': har[ :, 179 ],
    'tBodyGyroJerkMag-min()': har[ :, 180 ],
    'tBodyGyroJerkMag-sma()': har[ :, 181 ],
    'tBodyGyroJerkMag-energy()': har[ :, 182 ],
    'ttBodyGyroJerkMag-iqr()': har[ :, 183 ],
    'tBodyGyroJerkMag-entropy()': har[ :, 184 ],
    'fBodyAcc-mean()-X': har[ :, 185 ],
    'fBodyAcc-mean()-Y': har[ :, 186 ],
    'fBodyAcc-mean()-Z': har[ :, 187 ],
    'fBodyAcc-std()-X': har[ :, 188 ],
    'fBodyAcc-std()-Y': har[ :, 189 ],
    'fBodyAcc-std()-Z': har[ :, 190 ],
    'fBodyAcc-mad()-X': har[ :, 191 ],
    'fBodyAcc-mad()-Y': har[ :, 192 ],
    'fBodyAcc-mad()-Z': har[ :, 193 ],
    'fBodyAcc-max()-X': har[ :, 194 ],
    'fBodyAcc-max()-Y': har[ :, 195 ],
    'fBodyAcc-max()-Z': har[ :, 196 ],
    'fBodyAcc-min()-X': har[ :, 197 ],
    'fBodyAcc-min()-Y': har[ :, 198 ],
    'fBodyAcc-min()-Z': har[ :, 199 ],
    'fBodyAcc-sma()': har[ :, 200 ],
    'fBodyAcc-energy()-X': har[ :, 201 ],
    'fBodyAcc-energy()-Y': har[ :, 202 ],
    'fBodyAcc-energy()-Y': har[ :, 203 ],
    'fBodyAcc-iqr()-X': har[ :, 204 ],
    'fBodyAcc-iqr()-Y': har[ :, 205 ],
    'fBodyAcc-iqr()-Z': har[ :, 206 ],
    'fBodyAcc-entropy()-X': har[ :, 207 ],
    'fBodyAcc-entropy()-Y': har[ :, 208 ],
    'fBodyAcc-entropy()-Z': har[ :, 209 ],
    'fBodyAcc--maxInds-X': har[ :, 210 ],
    'fBodyAcc--maxInds-Y': har[ :, 211],
    'fBodyAcc--maxInds-Z': har[ :, 212 ],
    'fBodyAcc--meanFreq-X': har[ :, 213 ],
    'fBodyAcc--meanFreq-Y': har[ :, 214 ],
    'fBodyAcc--meanFreq-Z': har[ :, 215 ],
    'fBodyAcc--skewness()-X': har[ :, 216 ],
    'fBodyAcc--kurtosis()-X': har[ :, 217 ],
    'fBodyAcc--skewness()-Y': har[ :, 218 ],
    'fBodyAcc--kurtosis()-Y': har[ :, 219 ],
    'fBodyAcc--skewness()-Z': har[ :, 220 ],
    'fBodyAcc--kurtosis()-Z': har[ :, 221 ],
    'fBodyAccJerk-mean()-X': har[ :, 222 ],
    'fBodyAccJerk-mean()-Y': har[ :, 223 ],
    'fBodyAccJerk-mean()-Z': har[ :, 224 ],
    'fBodyAccJerk-std()-X': har[ :, 225],
    'fBodyAccJerk-std()-Y': har[ :, 226 ],
    'fBodyAccJerk-std()-Z': har[ :, 227 ],
    'fBodyAccJerk-mad()-X': har[ :, 228 ],
    'fBodyAccJerk-mad()-Y': har[ :, 229 ],
    'fBodyAccJerk-mad()-Z': har[ :, 230 ],
    'fBodyAccJerk-max()-X': har[ :, 231 ],
    'fBodyAccJerk-max()-Y': har[ :, 232 ],
    'fBodyAccJerk-max()-Z': har[ :, 233 ],
    'fBodyAccJerk-min()-X': har[ :, 234 ],
    'fBodyAccJerk-min()-Y': har[ :, 235 ],
    'fBodyAccJerk-min()-Z': har[ :, 236 ],
    'fBodyAccJerk-sma()': har[ :, 237 ],
    'fBodyAccJerk-energy()-X': har[ :, 238 ],
    'fBodyAccJerk-energy()-Y': har[ :, 239 ],
    'fBodyAccJerk-energy()-Y': har[ :, 240 ],
    'fBodyAccJerk-iqr()-X': har[ :, 241 ],
    'fBodyAccJerk-iqr()-Y': har[ :, 242 ],
    'fBodyAccJerk-iqr()-Z': har[ :, 243 ],
    'fBodyAccJerk-entropy()-X': har[ :, 244 ],
    'fBodyAccJerk-entropy()-Y': har[ :, 245 ],
    'fBodyAccJerk-entropy()-Z': har[ :, 246 ],
    'fBodyAccJerk--maxInds-X': har[ :, 247 ],
    'fBodyAccJerk--maxInds-Y': har[ :, 248 ],
    'fBodyAccJerk--maxInds-Z': har[ :, 249 ],
    'fBodyAccJerk--meanFreq-X': har[ :, 250 ],
    'fBodyAccJerk--meanFreq-Y': har[ :, 251 ],
    'fBodyAccJerk--meanFreq-Z': har[ :, 252 ],
    'fBodyAccJerk--skewness()-X': har[ :, 253 ],
    'fBodyAccJerk--kurtosis()-X': har[ :, 254 ],
    'fBodyAccJerk--skewness()-Y': har[ :, 255 ],
    'fBodyAccJerk--kurtosis()-Y': har[ :, 256 ],
    'fBodyAccJerk--skewness()-Z': har[ :, 257 ],
    'fBodyAccJerk--kurtosis()-Z': har[ :, 258 ],
    'fBodyGyro-mean()-X': har[ :, 259 ],
    'fBodyGyro-mean()-Y': har[ :, 260 ],
    'fBodyGyro-mean()-Z': har[ :, 261 ],
    'fBodyGyro-std()-X': har[ :, 262 ],
    'fBodyGyro-std()-Y': har[ :, 263 ],
    'fBodyGyro-std()-Z': har[ :, 264 ],
    'fBodyGyro-mad()-X': har[ :, 265 ],
    'fBodyGyro-mad()-Y': har[ :, 266 ],
    'fBodyGyro-mad()-Z': har[ :, 267 ],
    'fBodyGyro-max()-X': har[ :, 268 ],
    'fBodyGyro-max()-Y': har[ :, 269 ],
    'fBodyGyro-max()-Z': har[ :, 270 ],
    'fBodyGyro-min()-X': har[ :, 271 ],
    'fBodyGyro-min()-Y': har[ :, 272 ],
    'fBodyGyro-min()-Z': har[ :, 273 ],
    'fBodyGyro-sma()': har[ :, 274 ],
    'fBodyGyro-energy()-X': har[ :, 275  ],
    'fBodyGyro-energy()-Y': har[ :, 276 ],
    'fBodyGyro-energy()-Y': har[ :, 277 ],
    'fBodyGyro-iqr()-X': har[ :, 278 ],
    'fBodyGyro-iqr()-Y': har[ :, 279 ],
    'fBodyGyro-iqr()-Z': har[ :, 280 ],
    'fBodyGyro-entropy()-X': har[ :, 281 ],
    'fBodyGyro-entropy()-Y': har[ :, 282 ],
    'fBodyGyro-entropy()-Z': har[ :, 283 ],
    'fBodyGyro--maxInds-X': har[ :, 284],
    'fBodyGyro--maxInds-Y': har[ :, 285 ],
    'fBodyGyro--maxInds-Z': har[ :, 286 ],
    'fBodyGyro--meanFreq-X': har[ :, 287 ],
    'fBodyGyro--meanFreq-Y': har[ :, 288 ],
    'fBodyGyro--meanFreq-Z': har[ :, 289 ],
    'fBodyGyro-skewness()-X': har[ :, 290 ],
    'fBodyGyro--kurtosis()-X': har[ :, 291 ],
    'fBodyGyro--skewness()-Y': har[ :, 292 ],
    'fBodyGyro--kurtosis()-Y': har[ :, 293 ],
    'fBodyGyro--skewness()-Z': har[ :, 294 ],
    'fBodyGyro--kurtosis()-Z': har[ :, 295 ],
    'fBodyAccMag-mean()': har[ :, 296 ],
    'fBodyAccMag-std()': har[ :, 297 ],
    'fBodyAccMag-mad()': har[ :, 298 ],
    'fBodyAccMag-max()': har[ :, 299 ],
    'fBodyAccMag-min()': har[ :, 300 ],
    'fBodyAccMag-sma()': har[ :, 301 ],
    'fBodyAccMag-energy()': har[ :, 302 ],
    'fBodyAccMag-iqr()': har[ :, 303 ],
    'fBodyAccMag-enropy()': har[ :, 304 ],
    'fBodyAccMag-maxInds()': har[ :, 305 ],
    'fBodyAccMag-meanFreq()': har[ :, 306 ],
    'fBodyAccMag-skewness()': har[ :, 307 ],
    'fBodyAccMag-kurtosis()': har[ :, 308 ],
    'fBodyBodyAccJerkMag-mean()': har[ :, 309 ],
    'fBodyBodyAccJerkMag-std()': har[ :, 310 ],
    'fBodyBodyAccJerkMag-mad()': har[ :, 311 ],
    'fBodBodyAccJerkMag-max()': har[ :, 312 ],
    'fBodyBodyAccJerkMag-min()': har[ :, 313 ],
    'fBodyBodyAccJerkMag-sma()': har[ :, 314 ],
    'fBodyBodyAccJerkMag-energy()': har[ :, 315 ],
    'fBodyBodyAccJerkMag-iqr()': har[ :, 316 ],
    'fBodyBodyAccJerkMag-enropy()': har[ :, 317 ],
    'fBodyBodyAccJerkMag-maxInds()': har[ :, 318 ],
    'fBodyBodyGyroMag-meanFreq()': har[ :, 319 ],
    'fBodyBodyGyroMag-skewness()': har[ :, 320 ],
    'fBodyBodyGyroMag-kurtosis()': har[ :, 321 ],
    'fBodyBodyGyroMag-mean()': har[ :, 322 ],
    'fBodyBodyGyroMag-std()': har[ :, 323 ],
    'fBodyBodyGyroMag-mad()': har[ :, 324 ],
    'fBodBodyGyroMag-max()': har[ :, 325 ],
    'fBodyBodyGyroMag-min()': har[ :, 326 ],
    'fBodyBodyGyroMag-sma()': har[ :, 327 ],
    'fBodyBodyGyroMag-energy()': har[ :, 328 ],
    'fBodyBodyGyroMag-iqr()': har[ :, 329 ],
    'fBodyBodyGyroMag-enropy()': har[ :, 330 ],
    'fBodyBodyGyroMag-maxInds()': har[ :, 331 ],
    'fBodyBodyGyroMag-meanFreq()': har[ :, 332 ],
    'fBodyBodyGyroMag-skewness()': har[ :, 333 ],
    'fBodyBodyGyroMag-kurtosis()': har[ :, 334 ],
    'fBodyBodyGyroJerkMag-mean()': har[ :, 335 ],
    'fBodyBodyGyroJerkMag-std()': har[ :, 336 ],
    'fBodyBodyGyroJerkMag-mad()': har[ :, 337 ],
    'fBodBodyGyroJerkMag-max()': har[ :, 338 ],
    'fBodyBodyGyroJerkMag-min()': har[ :, 339 ],
    'fBodyBodyGyroJerkMag-sma()': har[ :, 340 ],
    'fBodyBodyGyroJerkMag-energy()': har[ :, 341 ],
    'fBodyBodyGyroJerkMag-iqr()': har[ :, 342 ],
    'fBodyBodyGyroJerkMag-enropy()': har[ :, 343 ],
    'fBodyBodyGyroJerkMag-maxInds()': har[ :, 344 ],
    'fBodyBodyGyroJerkMag-meanFreq()': har[ :, 345 ],
    'fBodyBodyGyroJerkMag-skewness()': har[ :, 346 ],
    'fBodyBodyGyroJerkMag-kurtosis()': har[ :, 347 ],
    'action': har[ :, 348 ]
} )
data.head()

# Import train_test_split function
from sklearn.model_selection import train_test_split

X = data[ [ 'tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z', 'tBodyAcc-std()-X', 'tBodyAcc-std()-Y',
            'tBodyAcc-std()-Z', 'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y',
            'tBodyAcc-mad()-Z',
            'tBodyAcc-max()-X',
            'tBodyAcc-max()-Y',
            'tBodyAcc-max()-Z',
            'tBodyAcc-min()-X',
            'tBodyAcc-min()-Y',
            'tBodyAcc-min()-Z',
            'tBodyAcc-sma()',
            'tBodyAcc-energy()-X',
            'tBodyAcc-energy()-Y',
            'tBodyAcc-energy()-Y',
            'tBodyAcc-iqr()-X',
            'tBodyAcc-iqr()-Y',
            'tBodyAcc-iqr()-Z',
            'tBodyAcc-entropy()-X',
            'tBodyAcc-entropy()-Y',
            'tBodyAcc-entropy()-Z',
            'tBodyAcc-correlation()-X,Y',
            'tBodyAcc-correlation()-X,Z',
            'tBodyAcc-correlation()-Y,Z',
            'tGravityAcc-mean()-X',
            'tGravityAcc-mean()-Y',
            'tGravityAcc-mean()-Z',
            'tGravityAcc-std()-X',
            'tGravityAcc-std()-Y',
            'tGravityAcc-std()-Z',
            'tGravityAcc-mad()-X',
            'tGravityAcc-mad()-Y',
            'tGravityAcc-mad()-Z',
            'tGravityAcc-max()-X',
            'tGravityAcc-max()-Y',
            'tGravityAcc-max()-Z',
            'tGravityAcc-min()-X',
            'tGravityAcc-min()-Y', 'tGravityAcc-min()-Z',
            'tGravityAcc-sma()',
            'tGravityAcc-energy()-X',
            'tGravityAcc-energy()-Y',
            'tGravityAcc-energy()-Y',
            'tGravityAcc-iqr()-X',
            'tGravityAcc-iqr()-Y',
            'tGravityAcc-iqr()-Z',
            'tGravityAcc-entropy()-X',
            'tGravityAcc-entropy()-Y',
            'tGravityAcc-entropy()-Z',
            'tGravityAcc-correlation()-X,Y',
            'tGravityAcc-correlation()-X,Z',
            'tGravityAcc-correlation()-Y,Z',
            'tBodyAccJerk-mean()-X',
            'tBodyAccJerk-mean()-Y',
            'tBodyAccJerk-mean()-Z',
            'tBodyAccJerk-std()-X',
            'tBodyAccJerk-std()-Y',
            'tBodyAccJerk-std()-Z',
            'tBodyAccJerk-mad()-X',
            'tBodyAccJerk-mad()-Y',
            'tBodyAccJerk-mad()-Z',
            'tBodyAccJerk-max()-X',
            'tBodyAccJerk-max()-Y',
            'tBodyAccJerk-max()-Z',
            'tBodyAccJerk-min()-X',
            'tBodyAccJerk-min()-Y',
            'tBodyAccJerk-min()-Z',
            'tBodyAccJerk-sma()',
            'tBodyAccJerk-energy()-X',
            'tBodyAccJerk-energy()-Y',
            'tBodyAccJerk-energy()-Y',
            'tBodyAccJerk-iqr()-X',
            'tBodyAccJerk-iqr()-Y',
            'tBodyAccJerk-iqr()-Z',
            'tBodyAccJerk-entropy()-X',
            'tBodyAccJerk-entropy()-Y',
            'tBodyAccJerk-entropy()-Z',
            'tBodyAccJerk-correlation()-X,Y',
            'tBodyAccJerk-correlation()-X,Z',
            'tBodyAccJerk-correlation()-Y,Z',
            'tBodyGyro-mean()-X',
            'tBodyGyro-mean()-Y',
            'tBodyGyro-mean()-Z',
            'tBodyGyro-std()-X',
            'tBodyGyro-std()-Y',
            'tBodyGyro-std()-Z',
            'tBodyGyro-mad()-X',
            'tBodyGyro-mad()-Y',
            'tBodyGyro-mad()-Z',
            'tBodyGyro-max()-X',
            'tBodyGyro-max()-Y',
            'tBodyGyro-max()-Z',
            'tBodyGyro-min()-X',
            'tBodyGyro-min()-Y',
            'tBodyGyro-min()-Z',
            'tBodyGyro-sma()',
            'tBodyGyro-energy()-X',
            'tBodyGyro-energy()-Y',
            'tBodyGyro-energy()-Y',
            'tBodyGyro-iqr()-X',
            'tBodyGyro-iqr()-Y',
            'tBodyGyro-iqr()-Z',
            'tBodyGyro-entropy()-X',
            'tBodyGyro-entropy()-Y',
            'tBodyGyro-entropy()-Z',
            'tBodyGyro-correlation()-X,Y',
            'tBodyGyro-correlation()-X,Z',
            'tBodyGyro-correlation()-Y,Z',
            'tBodyGyroJerk-mean()-X',
            'tBodyGyroJerk-mean()-Y',
            'tBodyGyroJerk-mean()-Z',
            'tBodyGyroJerk-std()-X',
            'tBodyGyroJerk-std()-Y',
            'tBodyGyroJerk-std()-Z',
            'tBodyGyroJerk-mad()-X',
            'tBodyGyroJerk-mad()-Y',
            'tBodyGyroJerk-mad()-Z',
            'tBodyGyroJerk-max()-X',
            'tBodyGyroJerk-max()-Y',
            'tBodyGyroJerk-max()-Z',
            'tBodyGyroJerk-min()-X',
            'tBodyGyroJerk-min()-Y',
            'tBodyGyroJerk-min()-Z',
            'tBodyGyroJerk-sma()',
            'tBodyGyroJerk-energy()-X',
            'tBodyGyroJerk-energy()-Y',
            'tBodyGyroJerk-energy()-Y',
            'tBodyGyroJerk-iqr()-X',
            'tBodyGyroJerk-iqr()-Y',
            'tBodyGyroJerk-iqr()-Z',
            'tBodyGyroJerk-entropy()-X',
            'tBodyGyroJerk-entropy()-Y',
            'tBodyGyroJerk-entropy()-Z',
            'tBodyGyroJerk-correlation()-X,Y',
            'tBodyGyroJerk-correlation()-X,Z',
            'tBodyGyroJerk-correlation()-Y,Z',
            'tBodyAccMag-mean()',
            'tBodyAccMag-std()',
            'tBodyAccMag-mad()',
            'tBodyAccMag-max()',
            'tBodyAccMag-min()',
            'tBodyAccMag-sma()',
            'tBodyAccMag-energy()',
            'tBodyAccMag-iqr()',
            'tBodyAccMag-enropy()',
            'tGravityAccMag-mean()',
            'tGravityAccMag-std()',
            'tGravityAccMag-mad()',
            'tGravityAccMag-max()',
            'tGravityAccMag-min()',
            'tGravityAccMag-sma()',
            'tGravityAccMag-energy()',
            'tGravityAccMag-iqr()',
            'tGravityAccMag-entropy()',
            'tBodyAccJerkMag-mean()',
            'tBodyAccJerkMag-std()',
            'tBodyAccJerkMag-mad()',
            'tBodyAccJerkMag-max()',
            'tBodyAccJerkMag-min()',
            'tBodyAccJerkMag-sma()',
            'tBodyAccJerkMag-energy()',
            'ttBodyAccJerkMag-iqr()',
            'tBodyAccJerkMag-entropy()',
            'tBodyGyroMag-mean()',
            'tBodyGyroMag-std()',
            'tBodyGyroMag-mad()',
            'tBodyGyroMag-max()',
            'tBodyGyroMag-min()',
            'tBodyGyroMag-sma()',
            'tBodyGyroMag-energy()',
            'ttBodyGyroMag-iqr()',
            'tBodyGyroMag-entropy()',
            'tBodyGyroJerkMag-mean()',
            'tBodyGyroJerkMag-std()',
            'tBodyGyroJerkMag-mad()',
            'tBodyGyroJerkMag-max()',
            'tBodyGyroJerkMag-min()',
            'tBodyGyroJerkMag-sma()',
            'tBodyGyroJerkMag-energy()',
            'ttBodyGyroJerkMag-iqr()',
            'tBodyGyroJerkMag-entropy()',
            'fBodyAcc-mean()-X',
            'fBodyAcc-mean()-Y',
            'fBodyAcc-mean()-Z',
            'fBodyAcc-std()-X',
            'fBodyAcc-std()-Y',
            'fBodyAcc-std()-Z',
            'fBodyAcc-mad()-X',
            'fBodyAcc-mad()-Y',
            'fBodyAcc-mad()-Z',
            'fBodyAcc-max()-X',
            'fBodyAcc-max()-Y',
            'fBodyAcc-max()-Z',
            'fBodyAcc-min()-X',
            'fBodyAcc-min()-Y',
            'fBodyAcc-min()-Z',
            'fBodyAcc-sma()',
            'fBodyAcc-energy()-X',
            'fBodyAcc-energy()-Y',
            'fBodyAcc-energy()-Y',
            'fBodyAcc-iqr()-X',
            'fBodyAcc-iqr()-Y',
            'fBodyAcc-iqr()-Z',
            'fBodyAcc-entropy()-X',
            'fBodyAcc-entropy()-Y',
            'fBodyAcc-entropy()-Z',
            'fBodyAcc--maxInds-X',
            'fBodyAcc--maxInds-Y',
            'fBodyAcc--maxInds-Z',
            'fBodyAcc--meanFreq-X',
            'fBodyAcc--meanFreq-Y',
            'fBodyAcc--meanFreq-Z',
            'fBodyAcc--skewness()-X',
            'fBodyAcc--kurtosis()-X',
            'fBodyAcc--skewness()-Y',
            'fBodyAcc--kurtosis()-Y',
            'fBodyAcc--skewness()-Z',
            'fBodyAcc--kurtosis()-Z',
            'fBodyAccJerk-mean()-X',
            'fBodyAccJerk-mean()-Y',
            'fBodyAccJerk-mean()-Z',
            'fBodyAccJerk-std()-X',
            'fBodyAccJerk-std()-Y',
            'fBodyAccJerk-std()-Z',
            'fBodyAccJerk-mad()-X',
            'fBodyAccJerk-mad()-Y',
            'fBodyAccJerk-mad()-Z',
            'fBodyAccJerk-max()-X',
            'fBodyAccJerk-max()-Y',
            'fBodyAccJerk-max()-Z',
            'fBodyAccJerk-min()-X',
            'fBodyAccJerk-min()-Y',
            'fBodyAccJerk-min()-Z',
            'fBodyAccJerk-sma()',
            'fBodyAccJerk-energy()-X',
            'fBodyAccJerk-energy()-Y',
            'fBodyAccJerk-energy()-Y',
            'fBodyAccJerk-iqr()-X',
            'fBodyAccJerk-iqr()-Y',
            'fBodyAccJerk-iqr()-Z',
            'fBodyAccJerk-entropy()-X',
            'fBodyAccJerk-entropy()-Y',
            'fBodyAccJerk-entropy()-Z',
            'fBodyAccJerk--maxInds-X',
            'fBodyAccJerk--maxInds-Y',
            'fBodyAccJerk--maxInds-Z',
            'fBodyAccJerk--meanFreq-X',
            'fBodyAccJerk--meanFreq-Y',
            'fBodyAccJerk--meanFreq-Z',
            'fBodyAccJerk--skewness()-X',
            'fBodyAccJerk--kurtosis()-X',
            'fBodyAccJerk--skewness()-Y',
            'fBodyAccJerk--kurtosis()-Y',
            'fBodyAccJerk--skewness()-Z',
            'fBodyAccJerk--kurtosis()-Z',
            'fBodyGyro-mean()-X',
            'fBodyGyro-mean()-Y',
            'fBodyGyro-mean()-Z',
            'fBodyGyro-std()-X',
            'fBodyGyro-std()-Y',
            'fBodyGyro-std()-Z',
            'fBodyGyro-mad()-X',
            'fBodyGyro-mad()-Y',
            'fBodyGyro-mad()-Z',
            'fBodyGyro-max()-X',
            'fBodyGyro-max()-Y',
            'fBodyGyro-max()-Z',
            'fBodyGyro-min()-X',
            'fBodyGyro-min()-Y',
            'fBodyGyro-min()-Z',
            'fBodyGyro-sma()',
            'fBodyGyro-energy()-X',
            'fBodyGyro-energy()-Y',
            'fBodyGyro-energy()-Y',
            'fBodyGyro-iqr()-X',
            'fBodyGyro-iqr()-Y',
            'fBodyGyro-iqr()-Z',
            'fBodyGyro-entropy()-X',
            'fBodyGyro-entropy()-Y',
            'fBodyGyro-entropy()-Z',
            'fBodyGyro--maxInds-X',
            'fBodyGyro--maxInds-Y',
            'fBodyGyro--maxInds-Z',
            'fBodyGyro--meanFreq-X',
            'fBodyGyro--meanFreq-Y',
            'fBodyGyro--meanFreq-Z',
            'fBodyGyro-skewness()-X',
            'fBodyGyro--kurtosis()-X',
            'fBodyGyro--skewness()-Y',
            'fBodyGyro--kurtosis()-Y',
            'fBodyGyro--skewness()-Z',
            'fBodyGyro--kurtosis()-Z',
            'fBodyAccMag-mean()',
            'fBodyAccMag-std()',
            'fBodyAccMag-mad()',
            'fBodyAccMag-max()',
            'fBodyAccMag-min()',
            'fBodyAccMag-sma()',
            'fBodyAccMag-energy()',
            'fBodyAccMag-iqr()',
            'fBodyAccMag-enropy()',
            'fBodyAccMag-maxInds()',
            'fBodyAccMag-meanFreq()',
            'fBodyAccMag-skewness()',
            'fBodyAccMag-kurtosis()',
            'fBodyBodyAccJerkMag-mean()',
            'fBodyBodyAccJerkMag-std()',
            'fBodyBodyAccJerkMag-mad()',
            'fBodBodyAccJerkMag-max()',
            'fBodyBodyAccJerkMag-min()',
            'fBodyBodyAccJerkMag-sma()',
            'fBodyBodyAccJerkMag-energy()',
            'fBodyBodyAccJerkMag-iqr()',
            'fBodyBodyAccJerkMag-enropy()',
            'fBodyBodyAccJerkMag-maxInds()',
            'fBodyBodyGyroMag-meanFreq()',
            'fBodyBodyGyroMag-skewness()',
            'fBodyBodyGyroMag-kurtosis()',
            'fBodyBodyGyroMag-mean()',
            'fBodyBodyGyroMag-std()',
            'fBodyBodyGyroMag-mad()',
            'fBodBodyGyroMag-max()',
            'fBodyBodyGyroMag-min()',
            'fBodyBodyGyroMag-sma()',
            'fBodyBodyGyroMag-energy()',
            'fBodyBodyGyroMag-iqr()',
            'fBodyBodyGyroMag-enropy()',
            'fBodyBodyGyroMag-maxInds()',
            'fBodyBodyGyroMag-meanFreq()',
            'fBodyBodyGyroMag-skewness()',
            'fBodyBodyGyroMag-kurtosis()',
            'fBodyBodyGyroJerkMag-mean()',
            'fBodyBodyGyroJerkMag-std()',
            'fBodyBodyGyroJerkMag-mad()',
            'fBodBodyGyroJerkMag-max()',
            'fBodyBodyGyroJerkMag-min()',
            'fBodyBodyGyroJerkMag-sma()',
            'fBodyBodyGyroJerkMag-energy()',
            'fBodyBodyGyroJerkMag-iqr()',
            'fBodyBodyGyroJerkMag-enropy()',
            'fBodyBodyGyroJerkMag-maxInds()',
            'fBodyBodyGyroJerkMag-meanFreq()',
            'fBodyBodyGyroJerkMag-skewness()',
            'fBodyBodyGyroJerkMag-kurtosis()']]  # Features

y = data[ 'action' ]  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3 )  # 70% training and 30% test

# Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

# Create a Gaussian Classifier
clf = RandomForestClassifier( n_estimators=100 )    #default n = 100

# Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit( X_train, y_train )

test = clf.predict(X_train)

y_pred = clf.predict(X_test)

# visualize the feature importance.
import matplotlib.pyplot as plt
import seaborn as sns

# Creating a bar plot
feature_imp = pd.Series(clf.feature_importances_, index=('tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z', 'tBodyAcc-std()-X', 'tBodyAcc-std()-Y',
            'tBodyAcc-std()-Z', 'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y',
            'tBodyAcc-mad()-Z',
            'tBodyAcc-max()-X',
            'tBodyAcc-max()-Y',
            'tBodyAcc-max()-Z',
            'tBodyAcc-min()-X',
            'tBodyAcc-min()-Y',
            'tBodyAcc-min()-Z',
            'tBodyAcc-sma()',
            'tBodyAcc-energy()-X',
            'tBodyAcc-energy()-Y',
            'tBodyAcc-energy()-Y',
            'tBodyAcc-iqr()-X',
            'tBodyAcc-iqr()-Y',
            'tBodyAcc-iqr()-Z',
            'tBodyAcc-entropy()-X',
            'tBodyAcc-entropy()-Y',
            'tBodyAcc-entropy()-Z',
            'tBodyAcc-correlation()-X,Y',
            'tBodyAcc-correlation()-X,Z',
            'tBodyAcc-correlation()-Y,Z',
            'tGravityAcc-mean()-X',
            'tGravityAcc-mean()-Y',
            'tGravityAcc-mean()-Z',
            'tGravityAcc-std()-X',
            'tGravityAcc-std()-Y',
            'tGravityAcc-std()-Z',
            'tGravityAcc-mad()-X',
            'tGravityAcc-mad()-Y',
            'tGravityAcc-mad()-Z',
            'tGravityAcc-max()-X',
            'tGravityAcc-max()-Y',
            'tGravityAcc-max()-Z',
            'tGravityAcc-min()-X',
            'tGravityAcc-min()-Y', 'tGravityAcc-min()-Z',
            'tGravityAcc-sma()',
            'tGravityAcc-energy()-X',
            'tGravityAcc-energy()-Y',
            'tGravityAcc-energy()-Y',
            'tGravityAcc-iqr()-X',
            'tGravityAcc-iqr()-Y',
            'tGravityAcc-iqr()-Z',
            'tGravityAcc-entropy()-X',
            'tGravityAcc-entropy()-Y',
            'tGravityAcc-entropy()-Z',
            'tGravityAcc-correlation()-X,Y',
            'tGravityAcc-correlation()-X,Z',
            'tGravityAcc-correlation()-Y,Z',
            'tBodyAccJerk-mean()-X',
            'tBodyAccJerk-mean()-Y',
            'tBodyAccJerk-mean()-Z',
            'tBodyAccJerk-std()-X',
            'tBodyAccJerk-std()-Y',
            'tBodyAccJerk-std()-Z',
            'tBodyAccJerk-mad()-X',
            'tBodyAccJerk-mad()-Y',
            'tBodyAccJerk-mad()-Z',
            'tBodyAccJerk-max()-X',
            'tBodyAccJerk-max()-Y',
            'tBodyAccJerk-max()-Z',
            'tBodyAccJerk-min()-X',
            'tBodyAccJerk-min()-Y',
            'tBodyAccJerk-min()-Z',
            'tBodyAccJerk-sma()',
            'tBodyAccJerk-energy()-X',
            'tBodyAccJerk-energy()-Y',
            'tBodyAccJerk-energy()-Y',
            'tBodyAccJerk-iqr()-X',
            'tBodyAccJerk-iqr()-Y',
            'tBodyAccJerk-iqr()-Z',
            'tBodyAccJerk-entropy()-X',
            'tBodyAccJerk-entropy()-Y',
            'tBodyAccJerk-entropy()-Z',
            'tBodyAccJerk-correlation()-X,Y',
            'tBodyAccJerk-correlation()-X,Z',
            'tBodyAccJerk-correlation()-Y,Z',
            'tBodyGyro-mean()-X',
            'tBodyGyro-mean()-Y',
            'tBodyGyro-mean()-Z',
            'tBodyGyro-std()-X',
            'tBodyGyro-std()-Y',
            'tBodyGyro-std()-Z',
            'tBodyGyro-mad()-X',
            'tBodyGyro-mad()-Y',
            'tBodyGyro-mad()-Z',
            'tBodyGyro-max()-X',
            'tBodyGyro-max()-Y',
            'tBodyGyro-max()-Z',
            'tBodyGyro-min()-X',
            'tBodyGyro-min()-Y',
            'tBodyGyro-min()-Z',
            'tBodyGyro-sma()',
            'tBodyGyro-energy()-X',
            'tBodyGyro-energy()-Y',
            'tBodyGyro-energy()-Y',
            'tBodyGyro-iqr()-X',
            'tBodyGyro-iqr()-Y',
            'tBodyGyro-iqr()-Z',
            'tBodyGyro-entropy()-X',
            'tBodyGyro-entropy()-Y',
            'tBodyGyro-entropy()-Z',
            'tBodyGyro-correlation()-X,Y',
            'tBodyGyro-correlation()-X,Z',
            'tBodyGyro-correlation()-Y,Z',
            'tBodyGyroJerk-mean()-X',
            'tBodyGyroJerk-mean()-Y',
            'tBodyGyroJerk-mean()-Z',
            'tBodyGyroJerk-std()-X',
            'tBodyGyroJerk-std()-Y',
            'tBodyGyroJerk-std()-Z',
            'tBodyGyroJerk-mad()-X',
            'tBodyGyroJerk-mad()-Y',
            'tBodyGyroJerk-mad()-Z',
            'tBodyGyroJerk-max()-X',
            'tBodyGyroJerk-max()-Y',
            'tBodyGyroJerk-max()-Z',
            'tBodyGyroJerk-min()-X',
            'tBodyGyroJerk-min()-Y',
            'tBodyGyroJerk-min()-Z',
            'tBodyGyroJerk-sma()',
            'tBodyGyroJerk-energy()-X',
            'tBodyGyroJerk-energy()-Y',
            'tBodyGyroJerk-energy()-Y',
            'tBodyGyroJerk-iqr()-X',
            'tBodyGyroJerk-iqr()-Y',
            'tBodyGyroJerk-iqr()-Z',
            'tBodyGyroJerk-entropy()-X',
            'tBodyGyroJerk-entropy()-Y',
            'tBodyGyroJerk-entropy()-Z',
            'tBodyGyroJerk-correlation()-X,Y',
            'tBodyGyroJerk-correlation()-X,Z',
            'tBodyGyroJerk-correlation()-Y,Z',
            'tBodyAccMag-mean()',
            'tBodyAccMag-std()',
            'tBodyAccMag-mad()',
            'tBodyAccMag-max()',
            'tBodyAccMag-min()',
            'tBodyAccMag-sma()',
            'tBodyAccMag-energy()',
            'tBodyAccMag-iqr()',
            'tBodyAccMag-enropy()',
            'tGravityAccMag-mean()',
            'tGravityAccMag-std()',
            'tGravityAccMag-mad()',
            'tGravityAccMag-max()',
            'tGravityAccMag-min()',
            'tGravityAccMag-sma()',
            'tGravityAccMag-energy()',
            'tGravityAccMag-iqr()',
            'tGravityAccMag-entropy()',
            'tBodyAccJerkMag-mean()',
            'tBodyAccJerkMag-std()',
            'tBodyAccJerkMag-mad()',
            'tBodyAccJerkMag-max()',
            'tBodyAccJerkMag-min()',
            'tBodyAccJerkMag-sma()',
            'tBodyAccJerkMag-energy()',
            'ttBodyAccJerkMag-iqr()',
            'tBodyAccJerkMag-entropy()',
            'tBodyGyroMag-mean()',
            'tBodyGyroMag-std()',
            'tBodyGyroMag-mad()',
            'tBodyGyroMag-max()',
            'tBodyGyroMag-min()',
            'tBodyGyroMag-sma()',
            'tBodyGyroMag-energy()',
            'ttBodyGyroMag-iqr()',
            'tBodyGyroMag-entropy()',
            'tBodyGyroJerkMag-mean()',
            'tBodyGyroJerkMag-std()',
            'tBodyGyroJerkMag-mad()',
            'tBodyGyroJerkMag-max()',
            'tBodyGyroJerkMag-min()',
            'tBodyGyroJerkMag-sma()',
            'tBodyGyroJerkMag-energy()',
            'ttBodyGyroJerkMag-iqr()',
            'tBodyGyroJerkMag-entropy()',
            'fBodyAcc-mean()-X',
            'fBodyAcc-mean()-Y',
            'fBodyAcc-mean()-Z',
            'fBodyAcc-std()-X',
            'fBodyAcc-std()-Y',
            'fBodyAcc-std()-Z',
            'fBodyAcc-mad()-X',
            'fBodyAcc-mad()-Y',
            'fBodyAcc-mad()-Z',
            'fBodyAcc-max()-X',
            'fBodyAcc-max()-Y',
            'fBodyAcc-max()-Z',
            'fBodyAcc-min()-X',
            'fBodyAcc-min()-Y',
            'fBodyAcc-min()-Z',
            'fBodyAcc-sma()',
            'fBodyAcc-energy()-X',
            'fBodyAcc-energy()-Y',
            'fBodyAcc-energy()-Y',
            'fBodyAcc-iqr()-X',
            'fBodyAcc-iqr()-Y',
            'fBodyAcc-iqr()-Z',
            'fBodyAcc-entropy()-X',
            'fBodyAcc-entropy()-Y',
            'fBodyAcc-entropy()-Z',
            'fBodyAcc--maxInds-X',
            'fBodyAcc--maxInds-Y',
            'fBodyAcc--maxInds-Z',
            'fBodyAcc--meanFreq-X',
            'fBodyAcc--meanFreq-Y',
            'fBodyAcc--meanFreq-Z',
            'fBodyAcc--skewness()-X',
            'fBodyAcc--kurtosis()-X',
            'fBodyAcc--skewness()-Y',
            'fBodyAcc--kurtosis()-Y',
            'fBodyAcc--skewness()-Z',
            'fBodyAcc--kurtosis()-Z',
            'fBodyAccJerk-mean()-X',
            'fBodyAccJerk-mean()-Y',
            'fBodyAccJerk-mean()-Z',
            'fBodyAccJerk-std()-X',
            'fBodyAccJerk-std()-Y',
            'fBodyAccJerk-std()-Z',
            'fBodyAccJerk-mad()-X',
            'fBodyAccJerk-mad()-Y',
            'fBodyAccJerk-mad()-Z',
            'fBodyAccJerk-max()-X',
            'fBodyAccJerk-max()-Y',
            'fBodyAccJerk-max()-Z',
            'fBodyAccJerk-min()-X',
            'fBodyAccJerk-min()-Y',
            'fBodyAccJerk-min()-Z',
            'fBodyAccJerk-sma()',
            'fBodyAccJerk-energy()-X',
            'fBodyAccJerk-energy()-Y',
            'fBodyAccJerk-energy()-Y',
            'fBodyAccJerk-iqr()-X',
            'fBodyAccJerk-iqr()-Y',
            'fBodyAccJerk-iqr()-Z',
            'fBodyAccJerk-entropy()-X',
            'fBodyAccJerk-entropy()-Y',
            'fBodyAccJerk-entropy()-Z',
            'fBodyAccJerk--maxInds-X',
            'fBodyAccJerk--maxInds-Y',
            'fBodyAccJerk--maxInds-Z',
            'fBodyAccJerk--meanFreq-X',
            'fBodyAccJerk--meanFreq-Y',
            'fBodyAccJerk--meanFreq-Z',
            'fBodyAccJerk--skewness()-X',
            'fBodyAccJerk--kurtosis()-X',
            'fBodyAccJerk--skewness()-Y',
            'fBodyAccJerk--kurtosis()-Y',
            'fBodyAccJerk--skewness()-Z',
            'fBodyAccJerk--kurtosis()-Z',
            'fBodyGyro-mean()-X',
            'fBodyGyro-mean()-Y',
            'fBodyGyro-mean()-Z',
            'fBodyGyro-std()-X',
            'fBodyGyro-std()-Y',
            'fBodyGyro-std()-Z',
            'fBodyGyro-mad()-X',
            'fBodyGyro-mad()-Y',
            'fBodyGyro-mad()-Z',
            'fBodyGyro-max()-X',
            'fBodyGyro-max()-Y',
            'fBodyGyro-max()-Z',
            'fBodyGyro-min()-X',
            'fBodyGyro-min()-Y',
            'fBodyGyro-min()-Z',
            'fBodyGyro-sma()',
            'fBodyGyro-energy()-X',
            'fBodyGyro-energy()-Y',
            'fBodyGyro-energy()-Y',
            'fBodyGyro-iqr()-X',
            'fBodyGyro-iqr()-Y',
            'fBodyGyro-iqr()-Z',
            'fBodyGyro-entropy()-X',
            'fBodyGyro-entropy()-Y',
            'fBodyGyro-entropy()-Z',
            'fBodyGyro--maxInds-X',
            'fBodyGyro--maxInds-Y',
            'fBodyGyro--maxInds-Z',
            'fBodyGyro--meanFreq-X',
            'fBodyGyro--meanFreq-Y',
            'fBodyGyro--meanFreq-Z',
            'fBodyGyro-skewness()-X',
            'fBodyGyro--kurtosis()-X',
            'fBodyGyro--skewness()-Y',
            'fBodyGyro--kurtosis()-Y',
            'fBodyGyro--skewness()-Z',
            'fBodyGyro--kurtosis()-Z',
            'fBodyAccMag-mean()',
            'fBodyAccMag-std()',
            'fBodyAccMag-mad()',
            'fBodyAccMag-max()',
            'fBodyAccMag-min()',
            'fBodyAccMag-sma()',
            'fBodyAccMag-energy()',
            'fBodyAccMag-iqr()',
            'fBodyAccMag-enropy()',
            'fBodyAccMag-maxInds()',
            'fBodyAccMag-meanFreq()',
            'fBodyAccMag-skewness()',
            'fBodyAccMag-kurtosis()',
            'fBodyBodyAccJerkMag-mean()',
            'fBodyBodyAccJerkMag-std()',
            'fBodyBodyAccJerkMag-mad()',
            'fBodBodyAccJerkMag-max()',
            'fBodyBodyAccJerkMag-min()',
            'fBodyBodyAccJerkMag-sma()',
            'fBodyBodyAccJerkMag-energy()',
            'fBodyBodyAccJerkMag-iqr()',
            'fBodyBodyAccJerkMag-enropy()',
            'fBodyBodyAccJerkMag-maxInds()',
            'fBodyBodyGyroMag-meanFreq()',
            'fBodyBodyGyroMag-skewness()',
            'fBodyBodyGyroMag-kurtosis()',
            'fBodyBodyGyroMag-mean()',
            'fBodyBodyGyroMag-std()',
            'fBodyBodyGyroMag-mad()',
            'fBodBodyGyroMag-max()',
            'fBodyBodyGyroMag-min()',
            'fBodyBodyGyroMag-sma()',
            'fBodyBodyGyroMag-energy()',
            'fBodyBodyGyroMag-iqr()',
            'fBodyBodyGyroMag-enropy()',
            'fBodyBodyGyroMag-maxInds()',
            'fBodyBodyGyroMag-meanFreq()',
            'fBodyBodyGyroMag-skewness()',
            'fBodyBodyGyroMag-kurtosis()',
            'fBodyBodyGyroJerkMag-mean()',
            'fBodyBodyGyroJerkMag-std()',
            'fBodyBodyGyroJerkMag-mad()',
            'fBodBodyGyroJerkMag-max()',
            'fBodyBodyGyroJerkMag-min()',
            'fBodyBodyGyroJerkMag-sma()',
            'fBodyBodyGyroJerkMag-energy()',
            'fBodyBodyGyroJerkMag-iqr()',
            'fBodyBodyGyroJerkMag-enropy()',
            'fBodyBodyGyroJerkMag-maxInds()',
            'fBodyBodyGyroJerkMag-meanFreq()',
            'fBodyBodyGyroJerkMag-skewness()',
            'fBodyBodyGyroJerkMag-kurtosis()' ))
pd.Series
print("feature imp", feature_imp)
sns.barplot(x=feature_imp, y=feature_imp.index)
# Add labels to your graph
plt.xlabel('Feature Importance Score')
plt.ylabel('Features')
plt.title("Visualizing Important Features")
plt.legend()
plt.show()

#write feature importance to file

from window_slider import Slider
bucket_size = 50
overlap_count = 0
slider1 = Slider(bucket_size,overlap_count)
slider1.fit(feature_imp)

while True:
    x = slider1.slide()
    print(x)
    if slider1.reached_end_of_list(): break

#create a confusion matrix
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy train:",metrics.accuracy_score(y_train, test))
print("Accuracy test:",metrics.accuracy_score(y_test, y_pred))

#MCC
print("MCC test:",metrics.matthews_corrcoef(y_test,y_pred))

# The recall is intuitively the ability of the classifier to find all the positive samples.
print("Recall test average:",metrics.recall_score(y_test,y_pred, average='weighted', zero_division=1))

#Precision
print("precision test average:",metrics.precision_score(y_test,y_pred, average='weighted', zero_division=1))

#F1-score
print("f1-score test average:",metrics.f1_score(y_test,y_pred, average='weighted', zero_division=1))

